version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "05:00"
      timezone: "Pacific/Auckland"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
    assignees:
      - "taroj1205"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      major-dependencies:
        update-types:
          - "major"
      dev-tooling:
        patterns:
          - "vite-plus"
          - "ultracite"
          - "@shadcn/lint"
          - "@stylexjs/*-plugin"
          - "autoprefixer"
          - "cspell*"
        update-types:
          - "minor"
          - "patch"
      minor-and-patch-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "vite-plus"
          - "ultracite"
          - "@shadcn/lint"
          - "@stylexjs/*-plugin"
          - "autoprefixer"
          - "cspell*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "05:00"
      timezone: "Pacific/Auckland"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "taroj1205"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
